In [2]:
import os
import torch
import tensorflow as tf
from transformers import BertModel, BertTokenizer

In [17]:
# load the pretrained weights v1.1 1m pubmed
# the dropout are disabled when load from pretrained weights
biobert = BertModel.from_pretrained("./checkpoints/biobert_v1.1_pubmed_torch/")

In [18]:
# load the vocab
bbtokenizer_args = {
    "vocab_file": "./checkpoints/biobert_v1.1_pubmed_torch/vocab.txt",
    "do_lower_case": False,
}
bbtokenizer = BertTokenizer(**bbtokenizer_args)

In [24]:
s = torch.tensor([bbtokenizer.encode("hello!")])
print(s)

tensor([[  101, 19082,   106,   102]])
tensor([[  101, 19082,   106,   102]])


In [20]:
biobert(s)

(tensor([[[ 0.7242, -0.1039,  0.0192,  ...,  0.1609, -0.2369, -0.5974],
          [ 0.2919,  0.0670, -0.2050,  ...,  0.5589, -0.1604, -0.4478],
          [ 0.4824, -0.3979,  0.7928,  ...,  0.3987, -0.4961, -0.3968],
          ...,
          [-0.0324, -0.4119,  0.1128,  ...,  0.0787,  0.1704, -0.1205],
          [ 0.1298, -0.5243, -0.2380,  ..., -0.1857, -0.0589, -0.1187],
          [ 0.6889, -1.1951,  0.0164,  ...,  0.0487,  0.0782, -0.6735]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[-1.1786e-01,  1.1618e-02,  8.0940e-01, -1.0000e+00,  1.0000e+00,
          -1.0919e-01, -4.6828e-02,  7.8734e-01,  1.1523e-01, -6.2308e-02,
           7.5075e-01,  9.9946e-01, -8.4513e-01, -7.9798e-01,  2.4703e-02,
           1.9311e-02,  1.0000e+00, -1.4847e-01, -9.6751e-01,  6.3124e-02,
          -1.0195e-01, -8.8776e-01,  3.7027e-02,  9.9964e-01, -3.4163e-02,
           1.2133e-01,  9.9968e-01,  9.6715e-01, -6.5561e-02,  6.8279e-02,
          -6.9330e-03, -1.0000e+00,  9.9982e-01, -9.9972e